id: gitlab-wp

info:
  name: gitlab setup
  author: ELSFA7110
  severity: critical
  reference: https://twitter.com/sec715/status/1397924997457317897
  tags: rce,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}.gitlab-ci.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "MYSQL_ROOT_PASSWORD"
          - "MYSQL_USER"
          - "MYSQL_PASSWORD"                    
        part: body

      - type: status
        status:
          - 200